# Site settings
title: Kameryn J Williams
email: kameryn.j.w@gmail.com # change this?
description: > # this means to ignore newlines until "baseurl:"
  Professional website of Kameryn J Williams. Logic and mathematics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kamerynjw.github.io/website" # the base hostname & protocol for your site
twitter_username: kamerynjw
github_username: kamerynjw
remote_theme: diezcami/arctic-fox-theme

excerpt_separator: <!--more-->


# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

  
