# Site settings
title: Julia Kameryn Williams
email: kwilliams@simons-rock.edu # 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" 
url: "https://juliakw.net" # ditto prev comment
github_username: julia-kw
remote_theme: diezcami/arctic-fox-theme

excerpt_separator: <!--more-->


# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

# plugins:
#    - jekyll/scholar

# # bibliography stuff
# scholar:
# #  style: /assets/biblio.cls
#   locale: en

#   sort_by: none
#   order: ascending

#   group_by: none
#   group_order: ascending

#   source: ./_bibliography
#   bibliography: bib.bib
#   bibliography_template: "{{reference}}"

#   replace_strings: true
#   join_strings:    true

#   use_raw_bibtex_entry: false
#   bibtex_filters:
#   - superscript
#   - latex

#   details_dir:    bibliography
#   details_layout: bibtex.html
#   details_link:   Details

#   query: "@*" 


redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

  
